apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: portfolio-ingress
  namespace: portfolio
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  tls:
  - hosts:
    - mattdev0.tech
    - www.mattdev0.tech
    secretName: portfolio-tls-secret
  rules:
  - host: mattdev0.tech
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 80
      - path: /api/status
        pathType: Prefix
        backend:
          service:
            name: rust-api
            port:
              number: 8080
      - path: /api/spotify
        pathType: Prefix
        backend:
          service:
            name: rust-api
            port:
              number: 8080
      - path: /api/infrastructure
        pathType: Prefix
        backend:
          service:
            name: java-api
            port:
              number: 8081
      - path: /api/github
        pathType: Prefix
        backend:
          service:
            name: java-api
            port:
              number: 8081
  - host: www.mattdev0.tech
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 80
      - path: /api/status
        pathType: Prefix
        backend:
          service:
            name: rust-api
            port:
              number: 8080
      - path: /api/spotify
        pathType: Prefix
        backend:
          service:
            name: rust-api
            port:
              number: 8080
      - path: /api/infrastructure
        pathType: Prefix
        backend:
          service:
            name: java-api
            port:
              number: 8081
      - path: /api/github
        pathType: Prefix
        backend:
          service:
            name: java-api
            port:
              number: 8081
