server {
    server_name mattdev0.tech www.mattdev0.tech;

    # Include Portfolio Microservice routes
    include /etc/nginx/snippets/portfolio-locations.conf;

    # Include DevOps Control Center routes
    include /etc/nginx/snippets/devops-locations.conf;

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/mattdev0.tech/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/mattdev0.tech/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}

server {
    if ($host = www.mattdev0.tech) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    if ($host = mattdev0.tech) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    listen 80;
    server_name mattdev0.tech www.mattdev0.tech;
    return 404; # managed by Certbot
}
