name: Production Deployment

# Trigger the workflow only when pushing to the infra-setup branch
on:
  push:
    branches:
      - infra-setup

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Executing Remote SSH Commands to Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AZURE_HOST }}
          username: ${{ secrets.AZURE_USER }}
          key: ${{ secrets.AZURE_SSH_KEY }}
          port: 22
          script: |
            echo "Successfully connected to Azure Production Server."
            
            # Navigate to your monorepo directory
            cd ~/portfolio-monorepo
            
            # Ensure the server is locked to the correct branch and fetch the latest code
            git fetch origin infra-setup
            git checkout infra-setup
            git reset --hard origin/infra-setup
            
            # Force Docker to rebuild changed images and run detached
            sudo docker-compose up -d --build
            
            # Prune dangling layers to prevent the server disk from filling up over time
            sudo docker image prune -f
            
            echo "Deployment successfully executed!"